'''
Created on May 26, 2019

@author: malte
'''

IDS = [
   'user_id',
   'session_id',
   'timestamp',
   'item_id',
   ]

CAT_FEATURES = [
    'impressions',
    'platform',
    'city',
    'device',
    'session_last_action',
    'session_last_all_filter',
    'session_last_all_poi',
    'session_last_all_sort',
    'session_last_filter',
    'session_last_poi',
    'session_last_sort',
   ]

EASY_FEATURES = [
    'position',
    'num_impressions'
    ]

POP_FEATURES = [
    'pop_all',
    'pop_all_per_impression',
    'pop_click',
    'pop_click_per_deal',
    'pop_click_per_image',
    'pop_click_per_impression',
    'pop_click_per_rating',
    'pop_click_per_view',
    'pop_click_per_view_sessions',
    'pop_deal',
    'pop_deal_per_impression',
    'pop_image',
    'pop_image_per_impression',
    'pop_impressions',
    'pop_platform_all',
    'pop_platform_all_per_impression',
    'pop_platform_click',
    'pop_platform_click_per_deal',
    'pop_platform_click_per_image',
    'pop_platform_click_per_impression',
    'pop_platform_click_per_rating',
    'pop_platform_click_per_view',
    'pop_platform_click_per_view_sessions',
    'pop_platform_deal',
    'pop_platform_deal_per_impression',
    'pop_platform_image',
    'pop_platform_image_per_impression',
    'pop_platform_impressions',
    'pop_platform_rating',
    'pop_platform_rating_per_impression',
    'pop_platform_view',
    'pop_platform_view_per_impression',
    'pop_rating',
    'pop_rating_per_impression',
    'pop_view',
    'pop_view_per_impression',
]

PRICE_FEATURES = [
    'price_city_all_dist',
    'price_city_all_mean',
    'price_city_all_minmax_dist',
    'price_city_all_permean',
    'price_city_click_dist',
    'price_city_click_mean',
    'price_city_click_minmax_dist',
    'price_city_click_permean',
    'price_city_impressions_dist',
    'price_city_impressions_mean',
    'price_city_impressions_minmax_dist',
    'price_city_impressions_permean',
    'price_city_platform_all_dist',
    'price_city_platform_all_mean',
    'price_city_platform_all_minmax_dist',
    'price_city_platform_all_permean',
    'price_city_platform_click_dist',
    'price_city_platform_click_mean',
    'price_city_platform_click_minmax_dist',
    'price_city_platform_click_permean',
    'price_city_platform_impressions_dist',
    'price_city_platform_impressions_mean',
    'price_city_platform_impressions_minmax_dist',
    'price_city_platform_impressions_permean',
    'price_city_platform_view_dist',
    'price_city_platform_view_mean',
    'price_city_platform_view_minmax_dist',
    'price_city_platform_view_permean',
    'price_city_view_dist',
    'price_city_view_mean',
    'price_city_view_minmax_dist',
    'price_city_view_permean',
    'price_item_all_dist',
    'price_item_all_mean',
    'price_item_all_minmax_dist',
    'price_item_all_permean',
    'price_item_click_dist',
    'price_item_click_mean',
    'price_item_click_minmax_dist',
    'price_item_click_permean',
    'price_item_impressions_dist',
    'price_item_impressions_mean',
    'price_item_impressions_minmax_dist',
    'price_item_impressions_permean',
    'price_item_view_dist',
    'price_item_view_mean',
    'price_item_view_minmax_dist',
    'price_item_view_permean',
    'price_list_impressions_dist',
    'price_list_impressions_mean',
    'price_list_impressions_minmax_dist',
    'price_list_impressions_permean',
    'price_platform_all_dist',
    'price_platform_all_mean',
    'price_platform_all_minmax_dist',
    'price_platform_all_permean',
    'price_platform_click_dist',
    'price_platform_click_mean',
    'price_platform_click_minmax_dist',
    'price_platform_click_permean',
    'price_platform_impressions_dist',
    'price_platform_impressions_mean',
    'price_platform_impressions_minmax_dist',
    'price_platform_impressions_permean',
    'price_platform_view_dist',
    'price_platform_view_mean',
    'price_platform_view_minmax_dist',
    'price_platform_view_permean',
]

SESSION_FEATURES = [
    'session_all_count',
    'session_city_dwell',
    'session_city_dwell_max',
    'session_city_dwell_mean',
    'session_city_dwell_min',
    'session_city_max_step',
    'session_city_max_time',
    'session_city_min_step',
    'session_city_min_time',
    'session_click_count',
    'session_click_count_rel',
    'session_deals_count',
    'session_deals_count_rel',
    'session_destination_count',
    'session_destination_count_rel',
    'session_dwell',
    'session_dwell_max',
    'session_dwell_mean',
    'session_dwell_min',
    'session_filter_count',
    'session_filter_count_rel',
    'session_image_count',
    'session_image_count_rel',
    'session_info_count',
    'session_info_count_rel',
    'session_item_all_count',
    'session_item_all_count_rel',
    'session_item_all_linear',
    'session_item_all_mrr',
    'session_item_click_count',
    'session_item_click_count_rel',
    'session_item_click_linear',
    'session_item_click_mrr',
    'session_item_deals_count',
    'session_item_deals_count_rel',
    'session_item_deals_linear',
    'session_item_deals_mrr',
    'session_item_dwell',
    'session_item_dwell_max',
    'session_item_dwell_mean',
    'session_item_dwell_min',
    'session_item_image_count',
    'session_item_image_count_rel',
    'session_item_image_linear',
    'session_item_image_mrr',
    'session_item_info_count',
    'session_item_info_count_rel',
    'session_item_info_linear',
    'session_item_info_mrr',
    'session_item_max_step',
    'session_item_max_time',
    'session_item_min_step',
    'session_item_min_time',
    'session_item_rating_count',
    'session_item_rating_count_rel',
    'session_item_rating_linear',
    'session_item_rating_mrr',
    'session_poi_count',
    'session_poi_count_rel',
    'session_rating_count',
    'session_rating_count_rel',
    'session_search_count',
    'session_search_count_rel',
    'session_size',
    'session_sort_0',
    'session_sort_1',
    'session_sort_194',
    'session_sort_195',
    'session_sort_196',
    'session_sort_197',
    'session_sort_198',
    'session_sort_199',
    'session_sort_2',
    'session_sort_200',
    'session_sort_201',
    'session_sort_202',
    'session_sort_203',
    'session_sort_3',
    'session_sort_4',
    'session_sort_5',
    'session_sort_6',
    'session_sort_count',
    'session_sort_count_rel',
]

USER_FEATURES = [
    'user_all_count',
    'user_distance_all_last_mean',
    'user_distance_all_last_mean_dist',
    'user_distance_click_last_mean',
    'user_distance_click_last_mean_dist',
    'user_item_all_count',
    'user_item_all_count_rel',
    'user_price_all_city_all_permean_dist',
    'user_price_all_city_impressions_permean_dist',
    'user_price_all_city_platform_all_permean_dist',
    'user_price_all_city_platform_impressions_permean_dist',
    'user_price_all_mean',
    'user_price_all_mean_dist',
    'user_price_all_platform_all_permean_dist',
    'user_price_all_platform_impressions_permean_dist',
    'user_price_city_all_city_all_permean_dist',
    'user_price_city_all_city_impressions_permean_dist',
    'user_price_city_all_city_platform_all_permean_dist',
    'user_price_city_all_city_platform_impressions_permean_dist',
    'user_price_city_all_mean',
    'user_price_city_all_mean_dist',
    'user_price_city_all_platform_all_permean_dist',
    'user_price_city_all_platform_impressions_permean_dist',
    'user_price_city_click_city_click_permean_dist',
    'user_price_city_click_city_impressions_permean_dist',
    'user_price_city_click_city_platform_click_permean_dist',
    'user_price_city_click_city_platform_impressions_permean_dist',
    'user_price_city_click_mean',
    'user_price_city_click_mean_dist',
    'user_price_city_click_platform_click_permean_dist',
    'user_price_city_click_platform_impressions_permean_dist',
    'user_price_click_city_click_permean_dist',
    'user_price_click_city_impressions_permean_dist',
    'user_price_click_city_platform_click_permean_dist',
    'user_price_click_city_platform_impressions_permean_dist',
    'user_price_click_mean',
    'user_price_click_mean_dist',
    'user_price_click_platform_click_permean_dist',
    'user_price_click_platform_impressions_permean_dist',
    'user_rating_all_mean',
    'user_rating_all_mean_dist',
    'user_rating_click_mean',
    'user_rating_click_mean_dist',
]
USER_FEATURES_CRAWL = [
    'user_distance_all_last_mean',
    'user_distance_all_last_mean_dist',
    'user_distance_click_last_mean',
    'user_distance_click_last_mean_dist',
    ]


CRAWL_FEATURES = [
#     'ci_lat',
#     'ci_lng',
    'ci_stars',
    'ci_superior',
    'ci_partner',
    'ci_itemgroup',
    'ci_wifi_lobby',
    'ci_wifi_room',
    'ci_pool',
    'ci_spa',
    'ci_parking',
    'ci_pets',
    'ci_aircondition',
    'ci_restaurant',
    'ci_bar',
    'ci_gym',
    'ii_count',
    'ii_partner_count',
    'ii_partner_max',
    'ri_rating_index',
    'ri_rating_percentage',
    'ri_rating_count',
    'ri_rating_advertiser',
    'ri_tested',
    'ri_awards',
    'ri_hotel_condition',
    'ri_comfort',
    'ri_facilities',
    'ri_location',
    'ri_breakfast',
    'ri_value_for_money',
    'ri_room',
    'ri_food_and_drinks',
    'ri_cleanliness',
    'ri_service',
    'ci_rating_per_price',
    'ci_stars_per_price'
    ]

GEO_FEATURES = [
    'ci_lat',
    'ci_lng',
    'distance_city',
    'distance_city_norm',
    'distance_last',
    'distance_last_norm',
    'distance_last_per_price',
    'distance_last_per_price_norm',
    'distance_last_per_rating',
]

RANK_FEATURES = [
    'rank_distance',
    'rank_distance_price',
    'rank_distance_rating',
    'rank_pop_count',
    'rank_pop_relative',
    'rank_prices',
    'rank_rating',
    'rank_latent',
    'rank_sum',
]
RANK_FEATURES_CRAWL = [
    'rank_distance',
    'rank_distance_price',
    'rank_distance_rating',
    #'rank_rating_price',
]

META_FEATURES_MOST = [
    '1 Star',
    '2 Star',
    '3 Star',
    '4 Star',
    '5 Star',
    'Accessible Hotel',
    'Accessible Parking',
    'Air Conditioning',
    'Airport Hotel',
    'Airport Shuttle',
    'All Inclusive (Upon Inquiry)',
    'Balcony',
    'Bathtub',
    'Beach',
    'Bed & Breakfast',
    'Bungalows',
    'Camping Site',
    'Car Park',
    'Casa Rural (ES)',
    'Direct beach access',
    'Excellent Rating',
    'Family Friendly',
    'Free WiFi (Combined)',
    'Free WiFi (Rooms)',
    'Gay-friendly',
    'Good Rating',
    'Guest House',
    'Gym',
    'Health Retreat',
    'Hostal (ES)',
    'Hostel',
    'Hotel',
    'Hotel Bar',
    'House / Apartment',
    'Jacuzzi (Hotel)',
    'Luxury Hotel',
    'Motel',
    'Non-Smoking Rooms',
    'Pet Friendly',
    'Playground',
    'Pousada (BR)',
    'Reception (24/7)',
    'Resort',
    'Restaurant',
    'Romantic',
    'Room Service',
    'Satisfactory Rating',
    'Sauna',
    'Self Catering',
    'Serviced Apartment',
    'Shower',
    'Spa (Wellness Facility)',
    'Spa Hotel',
    'Swimming Pool (Combined Filter)',
    'Swimming Pool (Indoor)',
    'Swimming Pool (Outdoor)',
    'Terrace (Hotel)',
    'Very Good Rating',
    'Wheelchair Accessible',
    'features',
    'stars',
    'rating'
]



D2V_FEATURES = [
    'd2v_if_0',
    'd2v_if_1',
    'd2v_if_2',
    'd2v_if_3',
    'd2v_if_4',
    'd2v_if_5',
    'd2v_if_6',
    'd2v_if_7',
    'd2v_if_8',
    'd2v_if_9',
    'd2v_if_10',
    'd2v_if_11',
    'd2v_if_12',
    'd2v_if_13',
    'd2v_if_14',
    'd2v_if_15',
#     'd2v_if_16',
#     'd2v_if_17',
#     'd2v_if_18',
#     'd2v_if_19',
#     'd2v_if_20',
#     'd2v_if_21',
#     'd2v_if_22',
#     'd2v_if_23',
#     'd2v_if_24',
#     'd2v_if_25',
#     'd2v_if_26',
#     'd2v_if_27',
#     'd2v_if_28',
#     'd2v_if_29',
#     'd2v_if_30',
#     'd2v_if_31',    
]

POS_FEATURES = [
    'pos_city_max',
    'pos_city_mean',
    'pos_city_mean_dist',
    'pos_city_min',
    'pos_city_platform_max',
    'pos_city_platform_mean',
    'pos_city_platform_mean_dist',
    'pos_city_platform_min',
    'pos_click_city_count',
    'pos_click_city_platform_count',
    'pos_click_city_platform_ratio',
    'pos_click_city_ratio',
    'pos_click_count',
    'pos_click_device_count',
    'pos_click_device_ratio',
    'pos_click_platform_count',
    'pos_click_platform_ratio',
    'pos_click_ratio',
    'pos_device_max',
    'pos_device_mean',
    'pos_device_mean_dist',
    'pos_device_min',
    'pos_invfilter_count',
    'pos_item_dist',
    'pos_item_max',
    'pos_item_mean',
    'pos_item_min',
    'pos_platform_max',
    'pos_platform_mean',
    'pos_platform_mean_dist',
    'pos_platform_min',
    'pos_session_2last',
    'pos_session_altering',
    'pos_session_click_2last',
    'pos_session_click_altering',
    'pos_session_click_direction',
    'pos_session_click_dist',
    'pos_session_click_last',
    'pos_session_click_max',
    'pos_session_click_mean',
    'pos_session_click_min',
    'pos_session_click_wrong_2last',
    'pos_session_click_wrong_altering',
    'pos_session_click_wrong_direction',
    'pos_session_click_wrong_dist',
    'pos_session_click_wrong_last',
    'pos_session_click_wrong_max',
    'pos_session_click_wrong_mean',
    'pos_session_click_wrong_min',
    'pos_session_direction',
    'pos_session_dist',
    'pos_session_last',
    'pos_session_max',
    'pos_session_mean',
    'pos_session_min',
    'pos_session_wrong_2last',
    'pos_session_wrong_altering',
    'pos_session_wrong_direction',
    'pos_session_wrong_dist',
    'pos_session_wrong_last',
    'pos_session_wrong_max',
    'pos_session_wrong_mean',
    'pos_session_wrong_min',
]

PROPERTIES_FEATURES = [
    'filter_count',
    'filter_current_match_session',
    'filter_match_session',
    'properties_match_session_intersect',
    'properties_match_session_union',
]

LATENT_FEATURES = [
    'bprc_item_if_0',
    'bprc_item_if_1',
    'bprc_item_if_10',
    'bprc_item_if_11',
    'bprc_item_if_12',
    'bprc_item_if_13',
    'bprc_item_if_14',
    'bprc_item_if_15',
    'bprc_item_if_16',
    'bprc_item_if_17',
    'bprc_item_if_18',
    'bprc_item_if_19',
    'bprc_item_if_2',
    'bprc_item_if_20',
    'bprc_item_if_21',
    'bprc_item_if_22',
    'bprc_item_if_23',
    'bprc_item_if_24',
    'bprc_item_if_25',
    'bprc_item_if_26',
    'bprc_item_if_27',
    'bprc_item_if_28',
    'bprc_item_if_29',
    'bprc_item_if_3',
    'bprc_item_if_30',
    'bprc_item_if_31',
    'bprc_item_if_4',
    'bprc_item_if_5',
    'bprc_item_if_6',
    'bprc_item_if_7',
    'bprc_item_if_8',
    'bprc_item_if_9',
    'bprc_item_item_cold',
    'bprc_item_session_cold',
    'bprc_item_sf_0',
    'bprc_item_sf_1',
    'bprc_item_sf_10',
    'bprc_item_sf_11',
    'bprc_item_sf_12',
    'bprc_item_sf_13',
    'bprc_item_sf_14',
    'bprc_item_sf_15',
    'bprc_item_sf_16',
    'bprc_item_sf_17',
    'bprc_item_sf_18',
    'bprc_item_sf_19',
    'bprc_item_sf_2',
    'bprc_item_sf_20',
    'bprc_item_sf_21',
    'bprc_item_sf_22',
    'bprc_item_sf_23',
    'bprc_item_sf_24',
    'bprc_item_sf_25',
    'bprc_item_sf_26',
    'bprc_item_sf_27',
    'bprc_item_sf_28',
    'bprc_item_sf_29',
    'bprc_item_sf_3',
    'bprc_item_sf_30',
    'bprc_item_sf_31',
    'bprc_item_sf_4',
    'bprc_item_sf_5',
    'bprc_item_sf_6',
    'bprc_item_sf_7',
    'bprc_item_sf_8',
    'bprc_item_sf_9',
]

LATENT_SIM_FEATURES = [
    'latent_sim_bprc_click128',
    'latent_sim_bprc_click32',
    'latent_sim_bprc_item128',
    'latent_sim_bprc_item32',
    'latent_sim_d2v_click32',
    'latent_sim_d2v_item32',
]

COMBINE_FEATURES = [
    'combine_pop_click_per_impression_all_count',
    'combine_pop_click_per_view_all_count',
]

TIME_FEATURES = [
    'day',
    'hour',
    'hour_cat1',
    'hour_cat2',
]

RATIO_FEATURES = [
    'ratio_rating_click_city_count',
    'ratio_rating_click_city_ratio',
    'ratio_rating_click_count',
    'ratio_rating_click_device_count',
    'ratio_rating_click_device_ratio',
    'ratio_rating_click_platform_count',
    'ratio_rating_click_platform_ratio',
    'ratio_rating_click_ratio',
    'ratio_stars_click_city_count',
    'ratio_stars_click_city_ratio',
    'ratio_stars_click_count',
    'ratio_stars_click_device_count',
    'ratio_stars_click_device_ratio',
    'ratio_stars_click_platform_count',
    'ratio_stars_click_platform_ratio',
    'ratio_stars_click_ratio',
]


STACK_FEATURES = [
    'pred_ffnn2000f4_noshfl_adam',
    'pred_sklearn_logit_noshfl_val0.1_',
    'pred_sklearn_sgd_noshfl_val0.1_',
]

LIST_CONTEXT_FEATURES = [
    'lc_ci_stars_permean1',
    'lc_ci_stars_permean2',
    'lc_ci_stars_permean3',
    'lc_ci_stars_permean4',
    'lc_ci_stars_post1',
    'lc_ci_stars_post2',
    'lc_ci_stars_post3',
    #'lc_ci_stars_post4',
    'lc_ci_stars_pre1',
    'lc_ci_stars_pre2',
    'lc_ci_stars_pre3',
    #'lc_ci_stars_pre4',
    'lc_distance_last_permean1',
    'lc_distance_last_permean2',
    'lc_distance_last_permean3',
    'lc_distance_last_permean4',
    'lc_distance_last_post1',
    'lc_distance_last_post2',
    'lc_distance_last_post3',
    #'lc_distance_last_post4',
    'lc_distance_last_pre1',
    'lc_distance_last_pre2',
    'lc_distance_last_pre3',
    #'lc_distance_last_pre4',
    'lc_prices_permean1',
    'lc_prices_permean2',
    'lc_prices_permean3',
    'lc_prices_permean4',
    'lc_prices_post1',
    'lc_prices_post2',
    'lc_prices_post3',
    #'lc_prices_post4',
    'lc_prices_pre1',
    'lc_prices_pre2',
    'lc_prices_pre3',
    #'lc_prices_pre4',
    'lc_ri_rating_index_permean1',
    'lc_ri_rating_index_permean2',
    'lc_ri_rating_index_permean3',
    'lc_ri_rating_index_permean4',
    'lc_ri_rating_index_post1',
    'lc_ri_rating_index_post2',
    'lc_ri_rating_index_post3',
    #'lc_ri_rating_index_post4',
    'lc_ri_rating_index_pre1',
    'lc_ri_rating_index_pre2',
    'lc_ri_rating_index_pre3',
    #'lc_ri_rating_index_pre4',
    'lc_ri_rating_percentage_permean1',
    'lc_ri_rating_percentage_permean2',
    'lc_ri_rating_percentage_permean3',
    'lc_ri_rating_percentage_permean4',
    'lc_ri_rating_percentage_post1',
    'lc_ri_rating_percentage_post2',
    'lc_ri_rating_percentage_post3',
    #'lc_ri_rating_percentage_post4',
    'lc_ri_rating_percentage_pre1',
    'lc_ri_rating_percentage_pre2',
    'lc_ri_rating_percentage_pre3',
    #'lc_ri_rating_percentage_pre4',
]
LIST_CONTEXT_FEATURES_CRAWL = [
    'lc_distance_last_permean1',
    'lc_distance_last_permean2',
    'lc_distance_last_permean3',
    'lc_distance_last_permean4',
    'lc_distance_last_post1',
    'lc_distance_last_post2',
    'lc_distance_last_post3',
    #'lc_distance_last_post4',
    'lc_distance_last_pre1',
    'lc_distance_last_pre2',
    'lc_distance_last_pre3',
    'lc_ri_rating_percentage_permean1',
    'lc_ri_rating_percentage_permean2',
    'lc_ri_rating_percentage_permean3',
    'lc_ri_rating_percentage_permean4',
    'lc_ri_rating_percentage_post1',
    'lc_ri_rating_percentage_post2',
    'lc_ri_rating_percentage_post3',
    #'lc_ri_rating_percentage_post4',
    'lc_ri_rating_percentage_pre1',
    'lc_ri_rating_percentage_pre2',
    'lc_ri_rating_percentage_pre3',
    #'lc_ri_rating_percentage_pre4',
    ]

FEATURES = []
FEATURES += CAT_FEATURES
FEATURES += EASY_FEATURES
FEATURES += POP_FEATURES
FEATURES += PRICE_FEATURES
FEATURES += SESSION_FEATURES
FEATURES += USER_FEATURES
FEATURES += CRAWL_FEATURES
FEATURES += GEO_FEATURES

FEATURES += META_FEATURES_MOST
FEATURES += D2V_FEATURES
#FEATURES += META_FEATURES_ALL

FEATURES += POS_FEATURES
FEATURES += PROPERTIES_FEATURES
#FEATURES += LATENT_FEATURES
FEATURES += LATENT_SIM_FEATURES
FEATURES += COMBINE_FEATURES
FEATURES += TIME_FEATURES
FEATURES += RATIO_FEATURES
#FEATURES += STACK_FEATURES
FEATURES += RANK_FEATURES
FEATURES += LIST_CONTEXT_FEATURES

WO_CRAWL = []
WO_CRAWL += CAT_FEATURES
WO_CRAWL += EASY_FEATURES
WO_CRAWL += POP_FEATURES
WO_CRAWL += PRICE_FEATURES
WO_CRAWL += SESSION_FEATURES
WO_CRAWL += USER_FEATURES
for f in USER_FEATURES_CRAWL:
    WO_CRAWL.remove(f)
    
WO_CRAWL += POS_FEATURES

WO_CRAWL += META_FEATURES_MOST
WO_CRAWL += D2V_FEATURES

WO_CRAWL += PROPERTIES_FEATURES
WO_CRAWL += LATENT_SIM_FEATURES
WO_CRAWL += COMBINE_FEATURES
WO_CRAWL += TIME_FEATURES
WO_CRAWL += RATIO_FEATURES
WO_CRAWL += RANK_FEATURES
for f in RANK_FEATURES_CRAWL:
    WO_CRAWL.remove(f)

WO_CRAWL += LIST_CONTEXT_FEATURES
for f in LIST_CONTEXT_FEATURES_CRAWL:
    WO_CRAWL.remove(f)
